# base on https://github.com/sureshg/compose-desktop-sample/blob/main/.github/workflows/
name: Compose Desktop Build

on:
  push:
    tags:
      - '*'
    paths-ignore:
      - LICENSE
      - README.md
      - 'docs/**'
      - '.github/config/labels.yml'

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build Package
    timeout-minutes: 15
    continue-on-error: false
    # if: github.event_name  == 'pull_request'

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ windows-latest ]
        jdk: [ 17 ]

    steps:
      - name: Check out the source code
        uses: actions/checkout@v3

      - name: Set up OpenJDK ${{ matrix.jdk }}
        id: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: ${{ matrix.jdk }}

      - name: Cache Gradle dependencies
        uses: actions/cache@v3.0.8
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle Build
        working-directory: ./ComposeGroceries
        id: gradle-build
        run: ./gradlew packageDistributionForCurrentOS

      - name: Uploading ${{ matrix.os }} native package
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: |
           ./ComposeGroceries/build/compose/binaries/main/msi/
          if-no-files-found: error


  release:
    name: Release new version.
    needs: [ build ]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Check out the source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ffurrer2/extract-release-notes@v1.15.0
        id: extract_release_notes
        if: ${{ false }}

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: ".github/config/configuration.json"
          commitMode: true
          ignorePreReleases: ${{ !contains(github.ref, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download all the build artifacts
        uses: actions/download-artifact@v3
        with:
          path: release-artifacts

      - name: Github Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.github_release.outputs.changelog }}
          prerelease: ${{ contains(github.event.inputs.version, '-rc') || contains(github.event.inputs.version, '-b') || contains(github.event.inputs.version, '-a') }}
          files: |
            ./release-artifacts/release-artifacts/**
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}